### ISSUE TITLE
Reference only assemblies

### ISSUE THREAD

**Issue by jeremy-marcus** [CodeCavePro/RevitSDK#1]
When using `PackageReference` a nuget package can specify that assemblies are for compile-time only (they won't output to the `bin` folder) by being in a `/ref` folder rather than `/lib`. By changing the csproj to put assemblies in `/ref` the package would act the same as setting `Copy Local=No`.

Documentation for this feature is here: https://docs.microsoft.com/en-us/nuget/create-packages/select-assemblies-referenced-by-projects

**Comment by salaros** [comment]
Actually that's a good idea, I wasn't aware of such NuGet feature and was using a MSBuild target to avoid having those files in the output directory. Updated all the packages

THANKS
